#####################################################################################
# JC-ESP32P4-M3 (ESP32-P4 + ESP32-C6 Wi-Fi 6 / BLE) Headless WebUI Hotspot
#####################################################################################
[env:jc-esp32p4-m3]
board = jc-esp32p4-m3
board_build.partitions = custom_16Mb.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_speed = 115200

lib_ignore =
    ${env.lib_ignore}
    NimBLE-Arduino
    ESP-PN532BLE
    ESP PN532 BLE
    ESP PN32BLE
    ESP-PN532-UART
    ESP-PN532Killer
    ESP-Amiibolink
    ESP Amiibolink
    ESP-ChameleonUltra
    ESP Chameleon Ultra

build_src_filter =
    ${env.build_src_filter}
    -<modules/ble/>
    -<modules/ble_api/>
    -<modules/badusb_ble/>
    +<../boards/jc-esp32p4-m3>

build_flags =
    ${env.build_flags}
    -Iboards/jc-esp32p4-m3
    -D BOARD_HAS_PSRAM=1
    -D BOARD_MEMORY_TYPE_OPI=1
    -D HEADLESS=1
    -D JC_ESP32P4_M3=1
    -D LITE_VERSION=1
    -D NO_BLE=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D GROVE_SDA=7
    -D GROVE_SCL=8
